swagger: "2.0"

info:
  title: Keras Model Server
  version: "1.0"

paths:
  /mnist/classify:
    post:
      summary: Classify Digits
      description: Generates a greeting message from a post, such as curl -F file=@sample.png http://localhost:5000/mnist/classify
      operationId: mnist.post_image
      consumes:
        - multipart/form-data
      produces:
        - text/json;
      responses:
        200:
          description: classification response
          schema:
            type: string
          examples:
            "text/json": "{digit: 0}"
      parameters:
        - name: file
          in: formData
          description: Image file to classify as a digit.
          required: true
          type: file